<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Tableau de bord</title>
</head>
<body>
	<form action="dashboard.php" method="post">
		<input type="hidden" name="username">
	</form>
	<h3>Bonjour <?php echo $usernameSession['username'];?> !</h3>
	<h3>Vos articles publiés</h3>
	<?php foreach($publishedArticles as $key => $article): ?>
			
				
					<h4><?= $article['title'] ?></h4>
					<h4><?= $article['publication_date']; ?></h4>
					<form action="dashboard.php" method="get">
					<input type="hidden" name="id" value="<?=$article['id'];?>">
					<button type="input">supprimer</button>
					</form>
					<form action="edit-article2.php" method="get">
					<input type="hidden" name="idedit" value="<?=$article['id'];?>">
					<button type="input">modifier</button>
					</form>
				
			
	<?php endforeach;?>
	<h3>Publier un nouvel article</h3>
	<form action="dashboard.php" method="post" enctype="multipart/form-data">
		<input type='text' name='title' placeholder="titre">
		<input type='text' name='content' placeholder="contenu">
		<input type="hidden" name="MAX_FILE_SIZE" value="3000000">
		<input type="file" name="monFichier" accept="image/png, image/jpeg">
		<button type="submit">Publier</button>
	</form>
</body>
</html>