<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>accueil</title>
</head>
<body>
    <a href="signup.php">inscription</a>
    <a href="login.php">connexion</a>

    <?php foreach($allArticles as $key => $article): ?>
			
			<div class="home-post">
            <a href="http://localhost/projets/community_blog/article.php?id=<?=$article['postid'];?>"><h4><?= $article['title'] ?></h4></a>
            <h4>Publié le <?= $article['publication_date']; ?></h4>
            <h4>Par  <a href="http://localhost/projets/community_blog/writer.php?id=<?=$article['id'];?>"><?= $article['username']; ?></a></h4>
            <a href="http://localhost/projets/community_blog/article.php?id=<?=$article['postid'];?>"> <img class="home-post-img" src="http://localhost/projets/community_blog/uploads/<?= $article['image']; ?>"></a>
            </div>



<?php endforeach;?>
</body>
</html>