<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>accueil</title>
    <link href="style.css" rel="stylesheet">
</head>

<body>
    <?php
    if (!empty($_SESSION)) {
        include('nav_logged.phtml');
    } else {
        include('nav.phtml');
    }
    ?>
    <main>
        <h2>Derniers articles publiés</h2><br>
        <section id="latest-posts">
            <?php foreach ($allArticles as $key => $article) : ?>

                <div class="home-post">
                    <a href="http://localhost/projets/community_blog/article.php?id=<?= $article['postid']; ?>">
                        <h4><?= $article['title'] ?></h4>
                    </a>
                    <p>Publié le <?= $article['publication_date']; ?></p>
                    <h4>Par <a href="http://localhost/projets/community_blog/writer.php?id=<?= $article['id']; ?>"><?= $article['username']; ?></a></h4>
                    <a href="http://localhost/projets/community_blog/article.php?id=<?= $article['postid']; ?>"> <img class="home-post-img" src="http://localhost/projets/community_blog/uploads/<?= $article['image']; ?>"></a>
                </div>
            <?php endforeach; ?>
        </section>
    </main>
</body>
<footer>
    <p>Ceci est un footer</p>
</footer>

</html>