<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>connexion</title>
    <link href="style.css" rel="stylesheet">
</head>
<body>
<nav>
       <div id="name-site"> <a href="http://localhost/projets/community_blog/">
            community_blog</a>
        </div>
        <div id="nav-items">
    
</div>
</nav>
<div id="container-form-signup">
<h2>Connexion</h2>
<form action="login.php" method="post">
<input type="text" name="username">
<input type="password" name="password">
<button type="submit">connexion</button>
</form>
</div>
<footer id="footer-login">
    <p>Ceci est un footer</p>
</footer>
</body>

</html>