<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>connexion</title>
    <link href="style.css" rel="stylesheet">
</head>

<body>

    <?php
    if (!empty($_SESSION)) {
        include('nav_logged.phtml');
    } else {
        include('nav.phtml');
    }
    ?>


    <div id="container-form-signup">
        <h2>Connexion</h2>
        <form action="login.php" method="post">
            <input type="text" name="username">
            <input type="password" name="password">
            <button type="submit">connexion</button>
        </form>
    </div>
    <?php  include('footer.phtml'); ?>
</body>

</html>