<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>inscription</title>
    <link href="style.css" rel="stylesheet">
</head>
<body>
<nav>
        <div id="name-site">
            community_blog
        </div>
        <div id="nav-items">
    
    <a href="login.php">connexion</a>
</div>
</nav>
<div id="container-form-signup">
<h2>inscription</h2>
    <form action="signup.php" method="post">
        <input type="text" placeholder="username" name="username">
        <input type="password" placeholder="password" name="password">
        <button type="input">sign up</button>
    </form>
</div>
<footer id="footer-signup">
    <p>Ceci est un footer</p>
</footer>
</body>
</html>